{"uuid": "f4459943-70e3-4898-a28f-ed2fa337f800", "children": ["c5643f58-4645-472f-9c0a-3b0476a9f4b2"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom no such execution context: uniqueContextId not found\n  (Session info: chrome=114.0.5735.199)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x004FA813+48355]\n\t(No symbol) [0x0048C4B1]\n\t(No symbol) [0x00395358]\n\t(No symbol) [0x003889B0]\n\t(No symbol) [0x00387138]\n\t(No symbol) [0x003877AA]\n\t(No symbol) [0x00398417]\n\t(No symbol) [0x003999E1]\n\t(No symbol) [0x00399A80]\n\t(No symbol) [0x003E1F1B]\n\t(No symbol) [0x003E093C]\n\t(No symbol) [0x003DA536]\n\t(No symbol) [0x003B82DC]\n\t(No symbol) [0x003B93DD]\n\tGetHandleVerifier [0x0075AABD+2539405]\n\tGetHandleVerifier [0x0079A78F+2800735]\n\tGetHandleVerifier [0x0079456C+2775612]\n\tGetHandleVerifier [0x005851E0+616112]\n\t(No symbol) [0x00495F8C]\n\t(No symbol) [0x00492328]\n\t(No symbol) [0x0049240B]\n\t(No symbol) [0x00484FF7]\n\tBaseThreadInitThunk [0x76C27BA9+25]\n\tRtlInitializeExceptionChain [0x76FCBD2B+107]\n\tRtlClearBits [0x76FCBCAF+191]\n\n", "trace": "  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\.jenkins\\workspace\\Credkart_Git\\testCases\\conftest.py\", line 43, in setup\n    driver = webdriver.Chrome()\n             ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 209, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 293, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1708580155710, "stop": 1708580169564}], "start": 1708580155710, "stop": 1708580169911}